### ISSUE TITLE
cocos2dx 可以使用这个库吗？

### ISSUE THREAD

**Issue by rustist** [cloudwu/sproto#24]
cocos2dx 使用的是lua5.1，是否可以？

**Comment by cloudwu** [comment]
可以. 但注意整数的精度和 lua 版本有关. lua 5.3 支持 64bit.

**Comment by rustist** [comment]
@cloudwu 我测试了下，现在有个问题，我客户端版本是5.1，sproto代码里用了`bit32`这个库。
而5.1 没有这个库，有没有可以替代的？谢谢

**Comment by cloudwu** [comment]
你可以自己编译一个这个库. luajit 有 bit 库.

在 2015年3月10日 下午4:11，cc <notifications@github.com>写道：

> @cloudwu <https://github.com/cloudwu> 我测试了下，现在有个问题，我客户端版本是5.1，sproto代码里用了
> bit32这个库。
> 而5.1 没有这个库，有没有可以替代的？谢谢
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudwu/sproto/issues/24#issuecomment-78010896>.
>



-- 
http://blog.codingnow.com

**Comment by cloudwu** [comment]
今天的 patch  https://github.com/cloudwu/sproto/commit/d903e10503ae6c99b76d9002cc74ef51ace3c9e2  去掉了对 bit32 的依赖.

**Comment by cloudwu** [comment]
另外，在 cocos 的客户端里，你完全不必引入 sprotoparser  这个模块，因为你可以离线把协议编译成 binary 再在 cocos 客户端里加载它们。
