### ISSUE TITLE
不明白为什么不考虑字节存储顺序问题？

### ISSUE THREAD

**Issue by wolfand11** [cloudwu/sproto#25]
当客户端和服务器不同字节存储顺序，整数和unicode字符串数据都会出错。

**Comment by cloudwu** [comment]
你试过了 "当客户端和服务器不同字节存储顺序" 时会有问题?

**Comment by wolfand11** [comment]
@cloudwu 
我没试过。没仔细看，原来是在encode_integer todword 这些里面做的。
