### ISSUE TITLE
client:dispatch(resp) 可以获取协议名吗？

### ISSUE THREAD

**Issue by rustist** [cloudwu/sproto#27]
看testrpc.lua，
local type, session, response = client:dispatch(resp)

没有response的协议名字，想问下为什么这么设计，看server是有的？

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/wiki/Sproto

request 有， response 因为有 session 所以不需要。因为你本来就必须从 session 找到当初对应的 request 是什么，所以你自然就能知道协议名。

反之，如果你不需要 session, 那让所有的消息都是 request 就好了。

**Comment by rustist** [comment]
> 那让所有的消息都是 request 就好了

这个是在协议里定义吗？

**Comment by cloudwu** [comment]
你需要的是，不使用 request/response 形式，而是无论是从那边向另一边发送数据都是 request ，永远没有 response 。

如果你需要 request/response ，那么你应该在 request 的时候，把当前的环境用 session 关联起来，这样你获得 response 时，从 session 这个找回当初 request 的环境，名字什么的就不是问题。
