### ISSUE TITLE
数据压缩部分缓冲区预测

### ISSUE THREAD

**Issue by findstr** [cloudwu/sproto#42]
在pack函数中，对0压缩后的缓冲区大小预测为每2k多算2个byte的字节开销，如果数据流是如0x78（x8 byte）0x0 0x78（x7 byte）这样压缩算下来，每16byte就需要两个额外字节开销，如果理解有误请见谅

**Comment by cloudwu** [comment]
为什么不用代码试一下?

**Comment by findstr** [comment]
不好意思，刚刚测完
