### ISSUE TITLE
pack bug

### ISSUE THREAD

**Issue by lijian2233** [cloudwu/sproto#43]
static int
lpack(lua_State *L) {
	size_t sz=0;
	const void * buffer = getbuffer(L, 1, &sz);
	// the worst-case space overhead of packing is 2 bytes per 2 KiB of input (256 words = 2KiB).
	//size_t maxsz = (sz + 2047) / 2048 * 2 + sz;
        //if (sz % 8) == 6 then sz = sz +  2  end if (sz%8) == 7 then sz = sz + 1 end
       size_t maxsz = (sz + 2047) / 2048 * 2 + ((sz + 7) & (~7));
	void * output = lua_touserdata(L, lua_upvalueindex(1));
	int bytes;
	int osz = lua_tointeger(L, lua_upvalueindex(2));
	if (osz < maxsz) {
		output = expand_buffer(L, osz, maxsz);
	}
	bytes = sproto_pack(buffer, sz, output, maxsz);
	if (bytes > maxsz) {
		return luaL_error(L, "packing error, return size = %d", bytes);
	}
	lua_pushlstring(L, output, bytes);

	return 1;
}

maxsz计算错误。
unpacked (hex):  8a (x 30 bytes)
packed (hex):  ff 03 8a (x 30 bytes) 00 00

没有计算padding数据的大小

// the worst-case space overhead of packing is 2 bytes per 2 KiB of input (256 words = 2KiB).
压缩格式：
ff 1byte xx ...
1byte 最大值255, (255+1)*8 = 2Kib, 每2Kib需要额外的两个字节空间 ff ff。

(sz + 2047) / 2048 * 2 计算 the worst-case space overhead of packing is 2 bytes per 2 KiB of input (256 words = 2KiB)这个值, ((sz + 7) & (~7)) 8字节对齐，更精确的值是这样的 if (sz % 8) == 6 then sz = sz +  2  end if (sz%8) == 7 then sz = sz + 1 end。

**Comment by lijian2233** [comment]
local str = ""
for i=1, 30 do
	str = str .. "\x8a"
end

print(type(str), #str)
local str1 = sproto.pack(str)

会触发(bytes == 34 and maxsz == 32)
if (bytes > maxsz) {
return luaL_error(L, "packing error, return size = %d", bytes);
}

**Comment by lvzixun** [comment]
应该是在463行之前把sz做下8字节对齐就行了把。

**Comment by lijian2233** [comment]
8字节对齐就不会出问题了，就能满足使用了

**Comment by lijian2233** [comment]
size_t maxsz = (sz + 2047) / 2048 * 2 + (sz + 7) & (~7);
应该是 maxsz =  (sz + 2047) / 2048 * 2 + (sz + 7)/8*8

**Comment by lijian2233** [comment]
size_t maxsz = (sz + 2047) / 2048 * 2 + (sz + 7) & (~7);
或改为 size_t maxsz = (sz + 2047) / 2048 * 2 + ((sz + 7) & (~7));
运算优先级的问题

**Comment by lvzixun** [comment]
确实不能直接对`sz`直接对齐赋值，下面的`bytes = sproto_pack(buffer, sz, output, maxsz);` 会用到`sz`,如果赋值的话，将会出现访问越界。

**Comment by lijian2233** [comment]
对，不要修改sz, 只修改maxsz

**Comment by spin6lock** [comment]
@lvzixun 下次能不能不用tricks。。。看了好久才看出来是对齐。。。。ref：http://www.catch22.net/tuts/c-c-tricks
