### ISSUE TITLE
sproto pack有个判断可以精简

### ISSUE THREAD

**Issue by spin6lock** [cloudwu/sproto#45]
https://github.com/cloudwu/sproto/blob/master/sproto.c#L1171-L1173
输入：
origin = "0102030405060708090a0b0c0d0e"
sproto输出：
sproto_result = "ff010102030405060708090a0b0c0d0e0000" --18 
去掉7和6的判断：
my_result     = "ff0001020304050607083f090a0b0c0d0e" --17

**Comment by cloudwu** [comment]
这个判断是为了在最坏情况下的额外开销.

**Comment by cloudwu** [comment]
You can try
```
0102030405060708090a0b0c0d0e00000102030405060708
```

**Comment by spin6lock** [comment]
In [1]: a="ff020102030405060708090a0b0c0d0e00000102030405060708"

In [2]: b="ff0001020304050607083f090a0b0c0d0eff000102030405060708"

加判断后的确能够省一个字节，我没考虑到这情况。。
