### ISSUE TITLE
Readme中貌似没有对tag的递增步长详细说明

### ISSUE THREAD

**Issue by andyhu-hz** [cloudwu/sproto#47]
If n is odd, that means the tags is not continuous, and we should add current tag by (n+1)/2 .

1. 从这句可以看出n为偶数时tag是连续的，步长为1，但不明显。
blog里有一句很重要： 字段的 tag 从 0 开始累加，每处理一个字段，将 tag 加一。应该写进readme。

2.别人也不知道这种奇数行的作用究竟是什么，只是从example2 中看出会被忽略，不知道是否是这样。 
01 00 (skip id = 2).

初学者的一点建议，如果问的不对，请多多包涵。

**Comment by zhaorulysy** [comment]
云大的blog是很老的了。。没有及时更新的吧。。

**Comment by andy-hu-hz** [comment]
blog无需要更新，它记录了当地的思路，这个readme要写的明白一点，不然别人必须得去看blog才能弄的清楚算法。

**Comment by cloudwu** [comment]
readme 稍微改了一下.
