### ISSUE TITLE
readme中的疑问

### ISSUE THREAD

**Issue by lidashuang** [cloudwu/sproto#48]
```
.AddressBook {
    person 0 : *Person(id)  # (id) is optional, means Person.id is main index.
}
```
这个 
>　means Person.id is main index

是什么意思？什么场景下用这个

**Comment by cloudwu** [comment]
实现一个字典.

比如， 你想要一个

key -> { foobar : xxx , foobar2 :xxx } 的字典，

你可以定义成

形如 { key:xxx , foobar :xxx , foobar2 : xxx } 的类型的数组，并声明 key 为 main index 。

lua binding 里，会把 key 抽出来做索引。

**Comment by lidashuang** [comment]
:+1:
