### ISSUE TITLE
似乎编码还是有点问题，空表没有打进去

### ISSUE THREAD

**Issue by spin6lock** [cloudwu/sproto#49]
https://gist.github.com/1fd2e1f09d5622667705028da514f531 
还原出来obj里面的元素都不见了，期待是见到这几个元素都是空表。

update：
python这边比较吊诡，其中一个空表打进去了，其他的没有。参见https://github.com/spin6lock/python-sproto/pull/9 这个PR的test_basic.py，只有f打印出来了。看日志，sproto_decode传过来的tagname就只有f，但是python版encode函数里，f和其他空表一样，都是返回SPROTO_CB_NIL的

**Comment by cloudwu** [comment]
前天走得太急，改错了地方。只在 integer array 分支做了判断：给 args->index 传 -1 创建空表。

我刚才移动了这段代码。不过现在身边没有开发环境，也没有 key 提交代码。只能在浏览器 edit 提交，所以请帮忙 pull 下来检查一下。

**Comment by spin6lock** [comment]
赞，可以了
