### ISSUE TITLE
想测试下pbc binding和sproto，pbc集成成功，sproto报告module 'sproto.core' not found

### ISSUE THREAD

**Issue by owen200008** [cloudwu/sproto#52]
看pbc是在newlib里面注册protocal.c sproto没有注册，不知道这个sproto.core是在什么时候注册的？

**Comment by owen200008** [comment]
目前自己手动注册了 可以使用 不过感觉还是很奇怪，另外继承lpeg protocal 和 sproto 进来大家都定义newlib这种方式，这个很容易出错，是否有好的解决方式呢，为什么不直接调用register？不太明白，求解释

**Comment by cloudwu** [comment]
rtfm

把 lua 手册一个字一个字读一遍

**Comment by murat8505** [comment]
I need help, error not sproto.core

**Comment by qlxiao520** [comment]
https://my.oschina.net/CandyMi/blog/840717
