### ISSUE TITLE
关于sproto二进制8字节对齐

### ISSUE THREAD

**Issue by korialuo** [cloudwu/sproto#57]
云风您好！关于压缩sproto二进制一连串0的问题，我按照你这个blog上的方法压缩了，http://blog.codingnow.com/2014/07/ejoyproto.html
后来才发现，sproto序列化成二进制的时候默认没有按照8字节对齐，比如有内字符串，并且长度不是8字节的倍数的时候。这样解压后的二进制末尾就会多几个字节的0，虽然测试了一下并不影响反序列化，但是不知道会不会存在潜在的影响。请问，是否能加个参数，在sproto序列化的时候选择是否按8字节对齐？谢谢。

这是我按照您的方法写的压缩0的代码：
https://github.com/korialuo/skynet/blob/master/lualib-src/lua-lzc.c

**Comment by cloudwu** [comment]
编码和解码是对称的就可以了。

**Comment by korialuo** [comment]
目前编码和解码都是对称并且按照8个字节对齐的，但是如果sproto数据不是对齐的话，末尾就会多几个00，目前来看没啥影响，今后我再想个办法干掉末尾多出来的00吧。谢谢云风！
