### ISSUE TITLE
关于二维数组这么定义sproto

### ISSUE THREAD

**Issue by OpenGamex** [cloudwu/sproto#58]
cards ＝ ｛
    ｛1, 2, 3 },
      {2, 3, 5 },
      {4, 5, 6}
｝

看了sproto语法，好像没有这种二维数组的定义

**Comment by cloudwu** [comment]
不支持

**Comment by najoast** [comment]
替代方案:
1. 如果二级数组元素数量固定，可以展开成1组数组，再带一个二级数组的长度。
2. 如果二级数组元素数量不固定，也是展开成1组数组，同时再发一个表示每个二级数组长度的数组。

**Comment by najoast** [comment]
```
.Cards {
     data    0 : *integer
     length 1 : integer
}

cards = {
       data = {1,2,3,2,3,5,4,5,6},
       length = 3,
}
```
