### ISSUE TITLE
lpeg这个文件怎么没有，运行报错了

### ISSUE THREAD

**Issue by lindxsea** [cloudwu/sproto#64]
我下载sproto工程，make Linux 后，运行test.lua文件报错
lua: ./sprotoparser.lua:1: module 'lpeg' not found:
	no field package.preload['lpeg']
	no file '/usr/local/share/lua/5.3/lpeg.lua'
	no file '/usr/local/share/lua/5.3/lpeg/init.lua'
	no file '/usr/local/lib/lua/5.3/lpeg.lua'
	no file '/usr/local/lib/lua/5.3/lpeg/init.lua'
	no file './lpeg.lua'
	no file './lpeg/init.lua'
	no file '/usr/local/lib/lua/5.3/lpeg.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lpeg.so'

**Comment by murat8505** [comment]
how did you solve this problem?
