### ISSUE TITLE
Why not directly use Cap'n Proto?

### ISSUE THREAD

**Issue by dumblob** [cloudwu/sproto#76]
sproto seems very close to Cap'n Proto. Actually, Cap'n Proto is even mentioned at the description of packing.

Why should I choose sproto over Cap'n Proto?

**Comment by cloudwu** [comment]
cap’n proto is very similar with google proto buffers, and it designed for c++. Its performance depend on mapping the proto structure directly to c++ structure, so you hardly get the same performance on other dynamic languages.

And cap’n proto and proto buffers are both depend on code generations. You should generate codes for any new protocol.

sproto has much smaller codebase, simple to use and easier to do binding to other (dynamic) languages.

**Comment by dumblob** [comment]
Maybe I misunderstood, but C++ is actually as easily integrable as C to most of dynamic languages (even in languages like Golang). So the performance shall stay the same for any language (Cap'n Proto has also a C interface).

Maybe 4 years ago this was different, but now it seems to be like written above.

Regarding code generation I'm not sure what you mean by a "new protocol". Do you mean you need to generate the code after any change of the schema? If so, then of course. But that's the same for *sproto* as well, right? Or am I missing something?

**Comment by cloudwu** [comment]
sproto doesn’t need generate any code for schema, so if you change the schema, just update the schema file.

**Comment by dumblob** [comment]
Ok, that answers my question. Thank you!
