### ISSUE TITLE
readme中 fn 的问题

### ISSUE THREAD

**Issue by sendysucc** [cloudwu/sproto#82]
![image](https://user-images.githubusercontent.com/45776428/50394307-a0c17580-0797-11e9-878a-c7644775b8ce.png)

请问一下，这个fn 为啥是4，不是3呢？

**Comment by cloudwu** [comment]
```
04 00 (fn = 4)
00 00 (id = 0, value in data part)
52 00 (id = 1, value = 40)
01 00 (skip id = 2)
00 00 (id = 3, value in data part)
```

4 项，包括 skip id = 2 这一项。
