### ISSUE TITLE
是否有人已经有人做了自定义增加所有消息的公共部分？

### ISSUE THREAD

**Issue by facingwaller** [cloudwu/sproto#84]
所谓自定义增加所有消息的公共部分是指，在skynet示例中，您加入了session的设计。这个可以在socket通信中的sprotol部分的外面，但是是否也可以作为一个公共的基础字段添加到sproto中。
比如这样解析
.package {
	type 0 : integer
	session 1 : integer
       session_user_define 2: integer   # 自定义增加
}
免得在socket发送的二进制流中自己拼接控制部分。
如果已经有人做了。我就不重复做轮子了，如果这样的设计不好，也请回复。谢谢

**Comment by cloudwu** [comment]
package 结构除了 type session 外一直都有一个额外的 ud 字段随便你定义，看  https://github.com/cloudwu/sproto/blob/master/sproto.lua

**Comment by facingwaller** [comment]
谢谢.
